services:
  gateway:
    container_name: gateway_arch_sw
    build: gateway
    ports:
      - 8000:8080
    volumes:
      - ./gateway:/var/lib/eg

  keycloak:
    container_name: keycloak_arch_sw
    image: quay.io/keycloak/keycloak:19.0.1
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2

  localstack:
    container_name: localstack_arch_sw
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3,dynamodb
    ports:
      - 4566-4597:4566-4597
    volumes:
      - ./.docker/localstack_setup.sh:/docker-entrypoint-initaws.d/setup.sh
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TEMPDIR:-/tmp/localstack}:/temp/localstack

  core:
    container_name: core_arch_sw
    build: core/
    command: "sh -c init.sh"
    ports:
      - 4000:4000
    env_file:
      - core/.env
    volumes:
      - ./core/:/src/app
