http:
  port: 8080
apiEndpoints:
  core:
    host: "*"
    paths: "/api/core/*"
  idp:
    host: "*"
    paths: "/idp/*"
serviceEndpoints:
  idProvider:
    url: http://keycloak:8080/realms/pass-manager
  coreApi:
    url: http://core:4000
policies:
  - log
  - proxy
  - rewrite
  - cors
pipelines:
  coreApi:
    apiEndpoints:
      - core
    policies:
      - rewrite:
          - condition:
              name: regexpmatch
              match: ^/api/core/?(.*)$
            action:
              rewrite: /$1
      - cors:
          - action:
              origin: "*"
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: coreApi
              changeOrigin: true

  identityProvider:
    apiEndpoints:
      - idp
    policies:
      - rewrite:
          - condition:
              name: regexpmatch
              match: ^/idp/?(.*)$
            action:
              rewrite: /$1
      - cors:
          - action:
              origin: "*"
      - log:
          - action:
              message: ${req.method} ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: idProvider
              changeOrigin: true
